# MegaLinter configuration file
# See all available variables at https://megalinter.io/configuration/
---
APPLY_FIXES: all
DEFAULT_BRANCH: main
FILEIO_REPORTER: false
SHOW_ELAPSED_TIME: true
FILTER_REGEX_EXCLUDE: (megalinter-reports/)

# Linters configuration
YAML_PRETTIER: true
MARKDOWN_MARKDOWNLINT: true
PYTHON_BLACK: true
PYTHON_ISORT: true
JSON_PRETTIER: true

# Enable specific linters
ENABLE_LINTERS:
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_BLACK
  - PYTHON_ISORT
  - PYTHON_PYLINT
  - JSON_PRETTIER
  - BASH_SHELLCHECK
  - BASH_SHFMT

# Disable linters that might be too aggressive
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
