name: Git Auto Commit
description: Commits and pushes changes if there are any

inputs:
  commit_message:
    description: The commit message to use
    required: true
  file_pattern:
    description: Files to add (default is all changes)
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Commit and push changes
      shell: bash
      run: |
        set -e
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Add files using the provided pattern(s) directly
        git add ${{ inputs.file_pattern }}

        # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          git commit -m "${{ inputs.commit_message }}"

          # Push with retry logic (exponential backoff)
          max_attempts=4
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            echo "Push attempt $attempt of $max_attempts..."
            if git push; then
              echo "✓ Successfully pushed changes"
              exit 0
            fi

            if [ $attempt -lt $max_attempts ]; then
              wait_time=$((2 ** (attempt - 1)))
              echo "Push failed, retrying in ${wait_time}s..."
              sleep $wait_time
            fi
            attempt=$((attempt + 1))
          done

          echo "✗ Failed to push after $max_attempts attempts"
          exit 1
        else
          echo "No changes to commit"
        fi
